version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

  app:
    image: lvergara1/pruebatecnica:v1
    container_name: app-container
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/pruebaTecnica?authSource=admin
      NASA_API_KEY: DEMO_KEY
      NASA_API_URL: https://api.nasa.gov/planetary/apod
      CORS_ALLOWED_ORIGINS: "*"
      DOC_SWAGGER: http://ptb.luisvergara.dev/swagger-ui.html
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
